# -----------------------------------------------------------------------------
# Configuración principal de Django: aplicaciones instaladas, middleware,
# plantillas, base de datos, idioma, zona horaria y archivos estáticos.
# -----------------------------------------------------------------------------

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Ruta absoluta a la carpeta raíz del proyecto.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Estas variables son obligatorias en .env o en el entorno del servidor.
# No hay valores secretos ni configuraciones permisivas de respaldo.
SECRET_KEY = os.getenv('CLAVE_SECRETA_DJANGO', '').strip()
if len(SECRET_KEY) < 50 or SECRET_KEY.startswith('django-insecure-'):
    raise ImproperlyConfigured(
        'CLAVE_SECRETA_DJANGO debe ser una clave aleatoria de al menos 50 caracteres.'
    )

# Se aceptan únicamente "si" y "no" para evitar activar DEBUG por error.
modo_depuracion = os.getenv('MODO_DEPURACION', '').strip().lower()
if modo_depuracion not in ('si', 'no'):
    raise ImproperlyConfigured('MODO_DEPURACION debe ser "si" o "no".')
DEBUG = modo_depuracion == 'si'

# Cada dominio se declara sin esquema ni puerto, separado por comas.
ALLOWED_HOSTS = [
    dominio.strip() for dominio in os.getenv('DOMINIOS_PERMITIDOS', '').split(',')
    if dominio.strip()
]
if not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'DOMINIOS_PERMITIDOS debe incluir dominios concretos, sin comodín.'
    )

# En producción se exige HTTPS; las cookies de sesión y CSRF viajan solo por TLS.
# HSTS empieza con una hora para permitir verificar el despliegue antes de ampliarlo.
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 3600 if not DEBUG else 0


# Application definition

INSTALLED_APPS = [
    "personal",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'personal.context_processors.contexto_rol',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# Idioma y zona horaria configurados actualmente para Django.
LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Authentication
# URL utilizada para autenticar usuarios.
LOGIN_URL = '/login/'

# URL utilizada después de iniciar sesión.
LOGIN_REDIRECT_URL = '/accounts/profile/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
