# Generated by Django 6.1 on 2026-08-29 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modificado_por', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
            ],
        ),
    ]
