# Generated by Django 6.1 on 2026-08-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_historialsalario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(default='Sin departamento', max_length=100),
        ),
    ]
