# Generated by Django 4.2 on 2026-08-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_empleado_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='esta_activo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_laboral',
            field=models.CharField(choices=[('activo', 'Activo (Trabajando)'), ('despedido', 'Despedido'), ('renuncio', 'Renunció')], default='activo', max_length=20),
        ),
    ]
