# Generated by Django 6.1 on 2026-08-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_remove_empleado_esta_activo_empleado_estado_laboral'),
        ('personal', '0005_cargar_datos_iniciales'),
    ]

    operations = [
    ]
