# Generated by Django 6.1 on 2026-08-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_merge_20260830_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
    ]
