# Generated by Django 4.2 on 2026-09-12 18:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0007_alter_empleado_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre_completo']},
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('no_indica', 'Prefiere no indicar')], default='no_indica', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado_laboral',
            field=models.CharField(choices=[('activo', 'Activo'), ('despedido', 'Despedido'), ('renuncio', 'Renunció')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('junior', 'Junior'), ('semi_senior', 'Semi Senior'), ('senior', 'Senior'), ('jefatura', 'Jefatura'), ('gerencia', 'Gerencia')], max_length=20)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='personal.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('medico', 'Médico'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('aprobado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='personal.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('puntuacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='personal.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('es_actual', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_puestos', to='personal.empleado')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='personal.puesto')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_a_cargo', to='personal.empleado'),
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonificacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarios', to='personal.empleado')),
            ],
            options={
                'ordering': ['-mes_ano'],
                'unique_together': {('empleado', 'mes_ano')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('minutos_trabajados', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atraso', 'Atraso'), ('permiso', 'Permiso')], default='presente', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='personal.empleado')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
