# Generated by Django 4.2 on 2026-09-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atraso', 'Atraso'), ('permiso', 'Permiso'), ('descanso', 'Descanso'), ('feriado', 'Feriado')], default='presente', max_length=20),
        ),
    ]
