# Generated by Django 4.2 on 2026-09-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_asistencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('irrenunciable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
