# Generated by Django 4.2 on 2026-09-22 19:09

from django.db import migrations, models
import django.db.models.functions.datetime


def comprobar_duplicados(apps, schema_editor):
    # No se decide automáticamente qué liquidación histórica conservar.
    salario = apps.get_model('personal', 'Salario')
    duplicados = (salario.objects.using(schema_editor.connection.alias)
        .annotate(anio=django.db.models.functions.datetime.ExtractYear('mes_ano'),
                  mes=django.db.models.functions.datetime.ExtractMonth('mes_ano'))
        .values('empleado_id', 'anio', 'mes').annotate(total=models.Count('pk'))
        .filter(total__gt=1))
    if duplicados.exists():
        raise RuntimeError('Hay liquidaciones duplicadas por empleado y mes. Revísalas antes de aplicar 0012; no se ha eliminado ningún registro.')


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_feriado'),
    ]

    operations = [
        migrations.RunPython(comprobar_duplicados, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='salario',
            constraint=models.UniqueConstraint(models.F('empleado'), django.db.models.functions.datetime.ExtractYear('mes_ano'), django.db.models.functions.datetime.ExtractMonth('mes_ano'), name='salario_unico_empleado_mes'),
        ),
    ]
